VirtoCommerce/vc-module-notification

src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-journal-details.tpl.html

Missing "cc" and "bcc" fields in the notification blade in orders

Adding the "cc" and "bcc" fields to the notification blade in orders

---

src/VirtoCommerce.NotificationsModule.Data/Senders/NotificationSender.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationSenderUnitTests.cs

Technical PR. The same PR as to dev-3.0.0

#VP-2603 refactor schedule notification

---

src/VirtoCommerce.NotificationsModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3119

VP-3119: Fix logo

---

src/VirtoCommerce.NotificationsModule.Core/Types/TwoFactorSmsNotification.cs
src/VirtoCommerce.NotificationsModule.Web/Module.cs

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

#VP-4186 add token

---

src/VirtoCommerce.NotificationsModule.Data/Services/NotificationService.cs

When notification is not found we get a NullReferenceException exception.
Add checking for null
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

Fix NullReferenceException

---

src/VirtoCommerce.NotificationsModule.Data/Services/NotificationService.cs

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5334: Call ClearCache before publish event

---

samples/VirtoCommerce.NotificationsSampleModule.Web/VirtoCommerce.NotificationsSampleModule.Web.csproj

To copy to publish the folder finaly also.

VDS-455: Copy notfication templates to output folder

---

src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-journal-details.tpl.html

use CreateDate property for CreatedDate field

VP-6405: Notification creation time is incorrect

---

samples/VirtoCommerce.NotificationsSampleModule.Web/Scripts/blades/notifications-twitter-details.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/filter-detail.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-details.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-templates-list.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/directives/itemSearch.tpl.html

VP-6770: Replace panel action icons

---

samples/VirtoCommerce.NotificationsSampleModule.Web/Scripts/blades/notifications-twitter-details.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/filter-detail.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-details.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-edit-template.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-list.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-menu.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-template-render.js

VP-6864: Fix header icon

---

src/VirtoCommerce.NotificationsModule.Core/Types/VerificationEmailNotification.cs
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Module.cs

Register Email address verification template

VP-6889: Email address verification template management

---

src/VirtoCommerce.NotificationsModule.Core/VirtoCommerce.NotificationsModule.Core.csproj
src/VirtoCommerce.NotificationsModule.Data/VirtoCommerce.NotificationsModule.Data.csproj
src/VirtoCommerce.NotificationsModule.LiquidRenderer/VirtoCommerce.NotificationsModule.LiquidRenderer.csproj
src/VirtoCommerce.NotificationsModule.SendGrid/VirtoCommerce.NotificationsModule.SendGrid.csproj
src/VirtoCommerce.NotificationsModule.Smtp/VirtoCommerce.NotificationsModule.Smtp.csproj
src/VirtoCommerce.NotificationsModule.TemplateLoader.FileSystem/VirtoCommerce.NotificationsModule.TemplateLoader.FileSystem.csproj
src/VirtoCommerce.NotificationsModule.Twilio/VirtoCommerce.NotificationsModule.Twilio.csproj
src/VirtoCommerce.NotificationsModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-207
* 2 forgotten? projects added to publish to nuget.

PT-207: Enable Source link support

---

src/VirtoCommerce.NotificationsModule.Core/Services/INotificationSender.cs
src/VirtoCommerce.NotificationsModule.Data/Senders/NotificationSender.cs
src/VirtoCommerce.NotificationsModule.Web/Controllers/NotificationsController.cs
src/VirtoCommerce.NotificationsModule.Web/Localizations/de.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-journal.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/resources/notificationsModuleApi.js

Original project task is [VIR-9](https://virtocommerce.atlassian.net/secure/RapidBoard.jspa?rapidView=101&modal=detail&selectedIssue=VIR-9).

PT-1351, VIR-9: Resend notification button is added to the journal

---

src/VirtoCommerce.NotificationsModule.Web/Controllers/NotificationsController.cs
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-journal.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/notifications.js

https://virtocommerce.atlassian.net/browse/PT-2236
@tatarincev, do you have some other opinion on the required permissions?

PT-2237: Fix and add permissions to endpoints

---

src/VirtoCommerce.NotificationsModule.Core/ModuleConstants.cs
src/VirtoCommerce.NotificationsModule.LiquidRenderer/LiquidRenderOptions.cs
src/VirtoCommerce.NotificationsModule.LiquidRenderer/LiquidRendererBuilder.cs
src/VirtoCommerce.NotificationsModule.LiquidRenderer/LiquidTemplateRenderer.cs
src/VirtoCommerce.NotificationsModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-2080
also provided the option to further increase the limit via ```Notifications:LiquidRenderOptions:LoopLimit```

PT-2082 increased loop limit in Liquid renderer

---

.github/workflows/main.yml
.github/workflows/publish_nugets.yml
Directory.Build.props
samples/VirtoCommerce.NotificationsSampleModule.Tests/VirtoCommerce.NotificationsSampleModule.Tests.csproj
samples/VirtoCommerce.NotificationsSampleModule.Web/VirtoCommerce.NotificationsSampleModule.Web.csproj
src/VirtoCommerce.NotificationsModule.Core/VirtoCommerce.NotificationsModule.Core.csproj
src/VirtoCommerce.NotificationsModule.Data/VirtoCommerce.NotificationsModule.Data.csproj
src/VirtoCommerce.NotificationsModule.LiquidRenderer/VirtoCommerce.NotificationsModule.LiquidRenderer.csproj
src/VirtoCommerce.NotificationsModule.SendGrid/VirtoCommerce.NotificationsModule.SendGrid.csproj
src/VirtoCommerce.NotificationsModule.Smtp/VirtoCommerce.NotificationsModule.Smtp.csproj
src/VirtoCommerce.NotificationsModule.TemplateLoader.FileSystem/VirtoCommerce.NotificationsModule.TemplateLoader.FileSystem.csproj
src/VirtoCommerce.NotificationsModule.Twilio/VirtoCommerce.NotificationsModule.Twilio.csproj
src/VirtoCommerce.NotificationsModule.Web/VirtoCommerce.NotificationsModule.Web.csproj
src/VirtoCommerce.NotificationsModule.Web/module.manifest
tests/VirtoCommerce.NotificationsModule.Tests/VirtoCommerce.NotificationsModule.Tests.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json

Fixed linguistic errors in the loc file, rewrote some phrases to sound more natural
https://virtocommerce.atlassian.net/browse/PT-5014

docs: Fix language

---

tests/VirtoCommerce.NotificationsModule.Tests/IntegrationTests/NotificationSenderIntegrationTests.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationServiceUnitTests.cs
tests/VirtoCommerce.NotificationsModule.Tests/VirtoCommerce.NotificationsModule.Tests.csproj
tests/VirtoCommerce.NotificationsModule.Tests/secrets.json

Integration tests are fixed
https://virtocommerce.atlassian.net/browse/PT-188

PT-188: Integration tests are fixed

---

samples/VirtoCommerce.NotificationsSampleModule.Web/Module.cs
src/VirtoCommerce.NotificationsModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-7292

PT-7292: Remove redundant BuildServiceProvider from the module startup

---

src/VirtoCommerce.NotificationsModule.Web/Scripts/notifications.js

Remove attachments widget from the notification blade.
https://virtocommerce.atlassian.net/browse/PT-7644

PT-7644: Remove attachments widget from the notification blade

---

docs/index.md
samples/VirtoCommerce.NotificationsSampleModule.Web/VirtoCommerce.NotificationsSampleModule.Web.csproj
src/VirtoCommerce.NotificationsModule.LiquidRenderer/LiquidTemplateRenderer.cs
src/VirtoCommerce.NotificationsModule.LiquidRenderer/VirtoCommerce.NotificationsModule.LiquidRenderer.csproj

Bump Scriban to 5.5 to improve template liquid syntax support
https://virtocommerce.atlassian.net/browse/PT-8380

PT-8380: Bump Scriban to 5.5 to improve template liquid syntax support

---

src/VirtoCommerce.NotificationsModule.Data/Services/NotificationMessageSearchService.cs
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-journal.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-journal.tpl.html

https://virtocommerce.atlassian.net/browse/PT-9320

PT-9320: add search to notification feed

---

src/VirtoCommerce.NotificationsModule.Web/Localizations/ru.VirtoCommerce.Notifications.json

Added ru localization

---

src/VirtoCommerce.NotificationsModule.Data/ExportImport/NotificationsExportImport.cs
tests/VirtoCommerce.NotificationsModule.Tests/IntegrationTests/NotificationsExportImportManagerIntegrationTests.cs

fix: Error in notification module when user import sample data and related module is not installed.
https://virtocommerce.atlassian.net/browse/PT-9849

PT-9849: Error in notification module when user import sample

---

src/VirtoCommerce.NotificationsModule.Web/module.manifest

fix: Update module manifest
https://virtocommerce.atlassian.net/browse/PT-11547

PT-11547: Update module manifest

---

README.md
src/VirtoCommerce.NotificationsModule.Web/module.manifest

PT-11547: Update readme

---

VirtoCommerce.NotificationsModule.sln
samples/VirtoCommerce.NotificationsSampleModule.Tests/IntegrationTests/TwitterNotificationServiceIntegrationTest.cs
src/VirtoCommerce.NotificationsModule.Data/Senders/NotificationSender.cs
src/VirtoCommerce.NotificationsModule.LiquidRenderer/Filters/StandardFilters.cs
src/VirtoCommerce.NotificationsModule.Smtp/SmtpEmailNotificationMessageSender.cs
src/VirtoCommerce.NotificationsModule.Web/Controllers/NotificationsController.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/LiquidTemplateRendererUnitTests.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationSenderUnitTests.cs

fix: Cannot write DateTime with Kind=Local to PostgreSQL
fix: Empty message body when send email via Smtp
https://virtocommerce.atlassian.net/browse/PT-12334

PT-12334: Cannot write DateTime with Kind=Local to PostgreSQL

---

src/VirtoCommerce.NotificationsModule.Core/Model/EmailNotification.cs
src/VirtoCommerce.NotificationsModule.Core/Model/NotificationLayout.cs
src/VirtoCommerce.NotificationsModule.Core/Model/NotificationRenderContext.cs
src/VirtoCommerce.NotificationsModule.Core/Model/Search/NotificationLayoutSearchCriteria.cs
src/VirtoCommerce.NotificationsModule.Data.MySql/Migrations/20230711144205_AddLayoutIsDefault.Designer.cs
src/VirtoCommerce.NotificationsModule.Data.MySql/Migrations/20230711144205_AddLayoutIsDefault.cs
src/VirtoCommerce.NotificationsModule.Data.PostgreSql/Migrations/20230711144014_AddLayoutIsDefault.Designer.cs
src/VirtoCommerce.NotificationsModule.Data.PostgreSql/Migrations/20230711144014_AddLayoutIsDefault.cs
src/VirtoCommerce.NotificationsModule.Data.PostgreSql/Migrations/NotificationDbContextModelSnapshot.cs
src/VirtoCommerce.NotificationsModule.Data.SqlServer/Migrations/20230711133756_AddLayoutIsDefault.Designer.cs
src/VirtoCommerce.NotificationsModule.Data.SqlServer/Migrations/20230711133756_AddLayoutIsDefault.cs
src/VirtoCommerce.NotificationsModule.Data.SqlServer/Migrations/NotificationDbContextModelSnapshot.cs
src/VirtoCommerce.NotificationsModule.Data/Model/NotificationLayoutEntity.cs
src/VirtoCommerce.NotificationsModule.Data/Services/NotificationLayoutSearchService.cs
src/VirtoCommerce.NotificationsModule.LiquidRenderer/LiquidTemplateRenderer.cs
src/VirtoCommerce.NotificationsModule.Web/Controllers/NotificationLayoutsController.cs
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-layout-details.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-layout-details.tpl.html
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-layouts-list.tpl.html
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-edit-template.tpl.html
tests/VirtoCommerce.NotificationsModule.Tests/IntegrationTests/NotificationSenderIntegrationTests.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/LiquidTemplateRendererUnitTests.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationSenderUnitTests.cs

PT-11563: Add default layout selection

---

src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-template-render.js

fix: Empty preview in notification
https://virtocommerce.atlassian.net/browse/PT-12709

PT-12709: Empty preview in notification

---

src/VirtoCommerce.NotificationsModule.Core/Extensions/NotificationSearchServiceExtensions.cs
tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationSearchServiceUnitTests.cs

fix: Empty Store Notification log if send an email with Global Notification Template
https://virtocommerce.atlassian.net/browse/PT-13171

PT-13171: Empty Store Notification log

---

.github/workflows/module-ci.yml

feat: Replace HighwayThree on Virto Commerce
https://virtocommerce.atlassian.net/browse/PT-13230

PT-13230: Replace HighwayThree on Virto Commerce

---

.github/workflows/module-ci.yml
.github/workflows/module-sample-ci.yml
README.md

fix: Warning The set-output command is deprecated and will be disabled soon.
https://virtocommerce.atlassian.net/browse/PT-13230

PT-13230: Fix [warning]The set-output command is deprecated and will be disabled soon.

---

src/VirtoCommerce.NotificationsModule.Core/Types/RegistrationInvitationCustomerEmailNotification.cs
src/VirtoCommerce.NotificationsModule.Core/Types/RegistrationInvitationEmailNotification.cs
src/VirtoCommerce.NotificationsModule.Core/Types/RegistrationInvitationNotificationBase.cs
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-13765

PT-13765: add Invitation for Customer email notification

---

src/VirtoCommerce.NotificationsModule.Core/ModuleConstants.cs
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/ru.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notification-templates-list.js

https://virtocommerce.atlassian.net/browse/PT-13970
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.405.0-pr-148-f31e.zip

PT-13970: Use platform languages

---

src/VirtoCommerce.NotificationsModule.Data.MySql/Migrations/20240319150726_AddEmailNotificationMessageAttachments.Designer.cs
src/VirtoCommerce.NotificationsModule.Data.MySql/Migrations/20240319150726_AddEmailNotificationMessageAttachments.cs
src/VirtoCommerce.NotificationsModule.Data.PostgreSql/Migrations/20240319150352_AddEmailNotificationMessageAttachments.Designer.cs
src/VirtoCommerce.NotificationsModule.Data.PostgreSql/Migrations/20240319150352_AddEmailNotificationMessageAttachments.cs
src/VirtoCommerce.NotificationsModule.Data.PostgreSql/Migrations/NotificationDbContextModelSnapshot.cs
src/VirtoCommerce.NotificationsModule.Data.SqlServer/Migrations/20240319083640_AddEmailNotificationMessageAttachments.Designer.cs
src/VirtoCommerce.NotificationsModule.Data.SqlServer/Migrations/20240319083640_AddEmailNotificationMessageAttachments.cs
src/VirtoCommerce.NotificationsModule.Data/Model/EmailAttachmentEntity.cs
src/VirtoCommerce.NotificationsModule.Data/Model/EmailNotificationEntity.cs
src/VirtoCommerce.NotificationsModule.Data/Model/EmailNotificationMessageEntity.cs
src/VirtoCommerce.NotificationsModule.Data/Repositories/NotificationDbContext.cs
src/VirtoCommerce.NotificationsModule.Data/Repositories/NotificationRepository.cs
src/VirtoCommerce.NotificationsModule.Data/Senders/NotificationSender.cs
src/VirtoCommerce.NotificationsModule.SendGrid/SendGridEmailNotificationMessageSender.cs

This change is necessary so that you can change the mechanism for generating the final email message before sending it
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.801.0-pr-152-501e.zip

Added a virtual method to convert an email message before sending it to SendGrid

---

src/VirtoCommerce.NotificationsModule.LiquidRenderer/VirtoCommerce.NotificationsModule.LiquidRenderer.csproj

The change consists only of updating the version of Scriban library from 5.9.0 to 5.10.0

updating scriban version to 5.10.0

---

src/VirtoCommerce.NotificationsModule.Web/Localizations/de.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/es.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/fr.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/it.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/ja.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/pl.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/pt.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/ru.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/zh.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Scripts/notifications.js

fix: Some titles are not localized
https://virtocommerce.atlassian.net/browse/VCST-2177
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.813.0-pr-167-4bf5.zip

VCST-2177: Some titles are not localized

---

src/VirtoCommerce.NotificationsModule.Smtp/SmtpEmailNotificationMessageSender.cs

fix: Added support for "Name" <email@example.com> email addresses.
https://virtocommerce.atlassian.net/browse/VCST-2262
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.814.0-pr-169-ad37.zip

VCST-2262: Add support for "Name" <email@example.com>

---

VirtoCommerce.NotificationsModule.sln
src/VirtoCommerce.NotificationsModule.MicrosoftGraph/MicrosoftGraphEmailNotificationMessageSender.cs
src/VirtoCommerce.NotificationsModule.MicrosoftGraph/MicrosoftGraphSenderOptions.cs
src/VirtoCommerce.NotificationsModule.MicrosoftGraph/VirtoCommerce.NotificationsModule.MicrosoftGraph.csproj
src/VirtoCommerce.NotificationsModule.Web/Module.cs
src/VirtoCommerce.NotificationsModule.Web/VirtoCommerce.NotificationsModule.Web.csproj

Added MicrosoftGraph implementation for OAuth. (#170)
https://virtocommerce.atlassian.net/browse/VCST-2459
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.815.0-pr-171-cc64.zip

Added MicrosoftGraph implementation for OAuth. (#170)

---

src/VirtoCommerce.NotificationsModule.Web/Localizations/de.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/en.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/es.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/fr.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/it.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/ja.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/pl.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/pt.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/ru.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Localizations/zh.VirtoCommerce.Notifications.json
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-template-render.js
src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-template-render.tpl.html

https://virtocommerce.atlassian.net/browse/VCST-3155
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.819.0-pr-177-da87.zip

VCST-3155: view error when render failed

---

samples/VirtoCommerce.NotificationsSampleModule.Web/Module.cs
src/VirtoCommerce.NotificationsModule.Data/Services/NotificationLayoutRegistrar.cs

https://virtocommerce.atlassian.net/browse/VCST-3813
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.822.0-pr-179-6490.zip

VCST-3813: Catch DbUpdateException on module start

---

src/VirtoCommerce.NotificationsModule.Web/Scripts/blades/notifications-edit-template.js

fix: The script error when add new notification template
https://virtocommerce.atlassian.net/browse/VCST-4000
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.824.0-pr-180-b326.zip

VCST-4000: The script error when add new notification template
